# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/erle/ros_catkin_ws/src/std_msgs/msg/Bool.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Byte.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/ByteMultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Char.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/ColorRGBA.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Duration.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Empty.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Float32.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Float32MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Float64.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Float64MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Header.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int16.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int16MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int32.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int32MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int64.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int64MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int8.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Int8MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/MultiArrayDimension.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/MultiArrayLayout.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/String.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/Time.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt16.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt16MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt32.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt32MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt64.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt64MultiArray.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt8.msg;/home/erle/ros_catkin_ws/src/std_msgs/msg/UInt8MultiArray.msg"
services_str = ""
pkg_name = "std_msgs"
dependencies_str = ""
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "std_msgs;/home/erle/ros_catkin_ws/src/std_msgs/msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/home/erle/ros_catkin_ws/install_isolated/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
