set(_CATKIN_CURRENT_PACKAGE "diagnostic_analysis")
set(diagnostic_analysis_VERSION "1.8.8")
set(diagnostic_analysis_MAINTAINER "Austin Hendrix <namniart@gmail.com>, Brice Rebsamen <brice.rebsamen@gmail.com>")
set(diagnostic_analysis_BUILD_DEPENDS "diagnostic_msgs" "rosbag" "roslib" "rostest")
set(diagnostic_analysis_RUN_DEPENDS "diagnostic_msgs" "rosbag" "roslib")
set(diagnostic_analysis_DEPRECATED "")
set(diagnostic_analysis_BUILDTOOL_DEPENDS "catkin")
set(diagnostic_analysis_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")