set(_CATKIN_CURRENT_PACKAGE "class_loader")
set(class_loader_RUN_DEPENDS "boost" "libconsole-bridge-dev" "libpoco-dev")
set(class_loader_VERSION "0.3.2")
set(class_loader_MAINTAINER "Esteve Fernandez <esteve@osrfoundation.org>")
set(class_loader_BUILD_DEPENDS "boost" "libconsole-bridge-dev" "libpoco-dev" "cmake_modules")
set(class_loader_BUILDTOOL_DEPENDS "catkin")
set(class_loader_DEPRECATED "")
set(class_loader_BUILD_DEPENDS_cmake_modules_VERSION_GTE "0.3.3")
set(class_loader_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")