(cl:defpackage robot_blockly-srv
  (:use )
  (:export
   "SETCURRENTBLOCKID"
   "<SETCURRENTBLOCKID-REQUEST>"
   "SETCURRENTBLOCKID-REQUEST"
   "<SETCURRENTBLOCKID-RESPONSE>"
   "SETCURRENTBLOCKID-RESPONSE"
  ))

