set(_CATKIN_CURRENT_PACKAGE "tf2_py")
set(tf2_py_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(tf2_py_DEPRECATED "")
set(tf2_py_VERSION "0.5.12")
set(tf2_py_BUILD_DEPENDS "tf2" "rospy")
set(tf2_py_RUN_DEPENDS "tf2" "rospy")
set(tf2_py_BUILDTOOL_DEPENDS "catkin")