# CMake generated Testfile for 
# Source directory: /home/erle/ros_catkin_ws/src/ros_comm/rostest
# Build directory: /home/erle/ros_catkin_ws/build_isolated/rostest
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_rostest_rostest_test_hztest0.test "/home/erle/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest0.xml" "--return-code" "/home/erle/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest0.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/rostest/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/rostest/test/hztest0.test ")
ADD_TEST(_ctest_rostest_rostest_test_hztest.test "/home/erle/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest.xml" "--return-code" "/home/erle/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/rostest/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/rostest/test/hztest.test ")
ADD_TEST(_ctest_rostest_rostest_test_clean_master.test "/home/erle/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_clean_master.xml" "--return-code" "/home/erle/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_clean_master.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/rostest/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/rostest/test/clean_master.test ")
ADD_TEST(_ctest_rostest_rostest_test_distro_version.test "/home/erle/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_distro_version.xml" "--return-code" "/home/erle/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_distro_version.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/rostest/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/rostest/test/distro_version.test ")
