set(_CATKIN_CURRENT_PACKAGE "tf2_ros")
set(tf2_ros_VERSION "0.5.12")
set(tf2_ros_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(tf2_ros_BUILD_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "message_filters" "roscpp" "rosgraph" "rospy" "std_msgs" "tf2" "tf2_msgs" "tf2_py")
set(tf2_ros_RUN_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "message_filters" "roscpp" "rosgraph" "rospy" "std_msgs" "tf2" "tf2_msgs" "tf2_py")
set(tf2_ros_DEPRECATED "")
set(tf2_ros_BUILDTOOL_DEPENDS "catkin")
set(tf2_ros_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(tf2_ros_BUILD_DEPENDS_message_filters_VERSION_GTE "1.11.1")