# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/ActuatorControl.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/BatteryStatus.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/CamIMUStamp.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/CommandCode.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/ExtendedState.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/FileEntry.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/HomePosition.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/ManualControl.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/Mavlink.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/OpticalFlowRad.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/OverrideRCIn.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/ParamValue.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/PositionTarget.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/RCIn.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/RCOut.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/RadioStatus.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/State.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/VFR_HUD.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/Vibration.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/Waypoint.msg;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg/WaypointList.msg"
services_str = "/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/CommandBool.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/CommandHome.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/CommandInt.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/CommandLong.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/CommandTOL.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/CommandTriggerControl.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileChecksum.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileClose.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileList.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileMakeDir.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileOpen.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileRead.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileRemove.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileRemoveDir.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileRename.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileTruncate.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/FileWrite.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/ParamGet.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/ParamPull.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/ParamPush.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/ParamSet.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/SetMode.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/StreamRate.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/WaypointClear.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/WaypointGOTO.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/WaypointPull.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/WaypointPush.srv;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/srv/WaypointSetCurrent.srv"
pkg_name = "mavros_msgs"
dependencies_str = "geometry_msgs;std_msgs"
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "mavros_msgs;/home/erle/ros_catkin_ws/src/mavros/mavros_msgs/msg;geometry_msgs;/home/erle/ros_catkin_ws/install_isolated/share/geometry_msgs/cmake/../msg;std_msgs;/home/erle/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/home/erle/ros_catkin_ws/install_isolated/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
