set(_CATKIN_CURRENT_PACKAGE "openni_launch")
set(openni_launch_MAINTAINER "Julius Kammerl <jkammerl@willowgarage.com>, Jon Binney <jbinney@willowgarage.com>")
set(openni_launch_DEPRECATED "")
set(openni_launch_VERSION "1.9.6")
set(openni_launch_BUILD_DEPENDS "roslaunch")
set(openni_launch_RUN_DEPENDS "nodelet" "openni_camera" "rgbd_launch")
set(openni_launch_BUILDTOOL_DEPENDS "catkin")