set(_CATKIN_CURRENT_PACKAGE "diagnostics")
set(diagnostics_MAINTAINER "Brice Rebsamen <brice.rebsamen@gmail.com>, Austin Hendrix <namniart@gmail.com>")
set(diagnostics_DEPRECATED "")
set(diagnostics_VERSION "1.8.8")
set(diagnostics_BUILD_DEPENDS )
set(diagnostics_RUN_DEPENDS "diagnostic_aggregator" "diagnostic_analysis" "diagnostic_common_diagnostics" "diagnostic_updater" "self_test")
set(diagnostics_BUILDTOOL_DEPENDS "catkin")