// Generated by gencpp from file crab_msgs/apm_imu.msg
// DO NOT EDIT!


#ifndef CRAB_MSGS_MESSAGE_APM_IMU_H
#define CRAB_MSGS_MESSAGE_APM_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crab_msgs
{
template <class ContainerAllocator>
struct apm_imu_
{
  typedef apm_imu_<ContainerAllocator> Type;

  apm_imu_()
    : gyro()
    , accel()  {
      gyro.assign(0.0);

      accel.assign(0.0);
  }
  apm_imu_(const ContainerAllocator& _alloc)
    : gyro()
    , accel()  {
      gyro.assign(0.0);

      accel.assign(0.0);
  }



   typedef boost::array<double, 3>  _gyro_type;
  _gyro_type gyro;

   typedef boost::array<double, 3>  _accel_type;
  _accel_type accel;




  typedef boost::shared_ptr< ::crab_msgs::apm_imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crab_msgs::apm_imu_<ContainerAllocator> const> ConstPtr;

}; // struct apm_imu_

typedef ::crab_msgs::apm_imu_<std::allocator<void> > apm_imu;

typedef boost::shared_ptr< ::crab_msgs::apm_imu > apm_imuPtr;
typedef boost::shared_ptr< ::crab_msgs::apm_imu const> apm_imuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crab_msgs::apm_imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crab_msgs::apm_imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crab_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/erle/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'crab_msgs': ['/home/erle/spider_ws/src/crab_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crab_msgs::apm_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crab_msgs::apm_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crab_msgs::apm_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crab_msgs::apm_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crab_msgs::apm_imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crab_msgs::apm_imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crab_msgs::apm_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "219dfe77f451afa726b227b93ba2a106";
  }

  static const char* value(const ::crab_msgs::apm_imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x219dfe77f451afa7ULL;
  static const uint64_t static_value2 = 0x26b227b93ba2a106ULL;
};

template<class ContainerAllocator>
struct DataType< ::crab_msgs::apm_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crab_msgs/apm_imu";
  }

  static const char* value(const ::crab_msgs::apm_imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crab_msgs::apm_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] gyro\n\
float64[3] accel\n\
";
  }

  static const char* value(const ::crab_msgs::apm_imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crab_msgs::apm_imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gyro);
      stream.next(m.accel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct apm_imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crab_msgs::apm_imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crab_msgs::apm_imu_<ContainerAllocator>& v)
  {
    s << indent << "gyro[]" << std::endl;
    for (size_t i = 0; i < v.gyro.size(); ++i)
    {
      s << indent << "  gyro[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gyro[i]);
    }
    s << indent << "accel[]" << std::endl;
    for (size_t i = 0; i < v.accel.size(); ++i)
    {
      s << indent << "  accel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.accel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAB_MSGS_MESSAGE_APM_IMU_H
