// Generated by gencpp from file crab_msgs/GetLegIKSolver.msg
// DO NOT EDIT!


#ifndef CRAB_MSGS_MESSAGE_GETLEGIKSOLVER_H
#define CRAB_MSGS_MESSAGE_GETLEGIKSOLVER_H

#include <ros/service_traits.h>


#include <crab_msgs/GetLegIKSolverRequest.h>
#include <crab_msgs/GetLegIKSolverResponse.h>


namespace crab_msgs
{

struct GetLegIKSolver
{

typedef GetLegIKSolverRequest Request;
typedef GetLegIKSolverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLegIKSolver
} // namespace crab_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crab_msgs::GetLegIKSolver > {
  static const char* value()
  {
    return "aab6d4778f2d7a09001d31408c116ed3";
  }

  static const char* value(const ::crab_msgs::GetLegIKSolver&) { return value(); }
};

template<>
struct DataType< ::crab_msgs::GetLegIKSolver > {
  static const char* value()
  {
    return "crab_msgs/GetLegIKSolver";
  }

  static const char* value(const ::crab_msgs::GetLegIKSolver&) { return value(); }
};


// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolverRequest> should match 
// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolver > 
template<>
struct MD5Sum< ::crab_msgs::GetLegIKSolverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crab_msgs::GetLegIKSolverRequest> should match 
// service_traits::DataType< ::crab_msgs::GetLegIKSolver > 
template<>
struct DataType< ::crab_msgs::GetLegIKSolverRequest>
{
  static const char* value()
  {
    return DataType< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolverResponse> should match 
// service_traits::MD5Sum< ::crab_msgs::GetLegIKSolver > 
template<>
struct MD5Sum< ::crab_msgs::GetLegIKSolverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crab_msgs::GetLegIKSolverResponse> should match 
// service_traits::DataType< ::crab_msgs::GetLegIKSolver > 
template<>
struct DataType< ::crab_msgs::GetLegIKSolverResponse>
{
  static const char* value()
  {
    return DataType< ::crab_msgs::GetLegIKSolver >::value();
  }
  static const char* value(const ::crab_msgs::GetLegIKSolverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAB_MSGS_MESSAGE_GETLEGIKSOLVER_H
