// Generated by gencpp from file crab_msgs/LegJointsState.msg
// DO NOT EDIT!


#ifndef CRAB_MSGS_MESSAGE_LEGJOINTSSTATE_H
#define CRAB_MSGS_MESSAGE_LEGJOINTSSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crab_msgs
{
template <class ContainerAllocator>
struct LegJointsState_
{
  typedef LegJointsState_<ContainerAllocator> Type;

  LegJointsState_()
    : joint()  {
      joint.assign(0.0);
  }
  LegJointsState_(const ContainerAllocator& _alloc)
    : joint()  {
      joint.assign(0.0);
  }



   typedef boost::array<double, 3>  _joint_type;
  _joint_type joint;




  typedef boost::shared_ptr< ::crab_msgs::LegJointsState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crab_msgs::LegJointsState_<ContainerAllocator> const> ConstPtr;

}; // struct LegJointsState_

typedef ::crab_msgs::LegJointsState_<std::allocator<void> > LegJointsState;

typedef boost::shared_ptr< ::crab_msgs::LegJointsState > LegJointsStatePtr;
typedef boost::shared_ptr< ::crab_msgs::LegJointsState const> LegJointsStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crab_msgs::LegJointsState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crab_msgs::LegJointsState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crab_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/erle/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'crab_msgs': ['/home/erle/spider_ws/src/crab_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crab_msgs::LegJointsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crab_msgs::LegJointsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crab_msgs::LegJointsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crab_msgs::LegJointsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crab_msgs::LegJointsState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crab_msgs::LegJointsState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crab_msgs::LegJointsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c9183fb9f551c0c8a1fa0044edf51fc";
  }

  static const char* value(const ::crab_msgs::LegJointsState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c9183fb9f551c0cULL;
  static const uint64_t static_value2 = 0x8a1fa0044edf51fcULL;
};

template<class ContainerAllocator>
struct DataType< ::crab_msgs::LegJointsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crab_msgs/LegJointsState";
  }

  static const char* value(const ::crab_msgs::LegJointsState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crab_msgs::LegJointsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] joint\n\
";
  }

  static const char* value(const ::crab_msgs::LegJointsState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crab_msgs::LegJointsState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LegJointsState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crab_msgs::LegJointsState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crab_msgs::LegJointsState_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAB_MSGS_MESSAGE_LEGJOINTSSTATE_H
