set(_CATKIN_CURRENT_PACKAGE "nodelet")
set(nodelet_RUN_DEPENDS "bondcpp" "boost" "message_runtime" "pluginlib" "rosconsole" "roscpp" "std_msgs" "tinyxml" "uuid")
set(nodelet_VERSION "1.9.3")
set(nodelet_MAINTAINER "Esteve Fernandez <esteve@osrfoundation.org>")
set(nodelet_BUILD_DEPENDS "bondcpp" "boost" "cmake_modules" "message_generation" "pluginlib" "rosconsole" "roscpp" "rospy" "std_msgs" "tinyxml" "uuid")
set(nodelet_DEPRECATED "")
set(nodelet_BUILDTOOL_DEPENDS "catkin")
set(nodelet_RUN_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_BUILD_DEPENDS_cmake_modules_VERSION_GTE "0.3.2")
set(nodelet_BUILD_DEPENDS_pluginlib_VERSION_GTE "1.10.0")