// Generated by gencpp from file robot_blockly/SetCurrentBlockId.msg
// DO NOT EDIT!


#ifndef ROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKID_H
#define ROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKID_H

#include <ros/service_traits.h>


#include <robot_blockly/SetCurrentBlockIdRequest.h>
#include <robot_blockly/SetCurrentBlockIdResponse.h>


namespace robot_blockly
{

struct SetCurrentBlockId
{

typedef SetCurrentBlockIdRequest Request;
typedef SetCurrentBlockIdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCurrentBlockId
} // namespace robot_blockly


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_blockly::SetCurrentBlockId > {
  static const char* value()
  {
    return "4df111d1d4ad61c42177e2b8cae23a38";
  }

  static const char* value(const ::robot_blockly::SetCurrentBlockId&) { return value(); }
};

template<>
struct DataType< ::robot_blockly::SetCurrentBlockId > {
  static const char* value()
  {
    return "robot_blockly/SetCurrentBlockId";
  }

  static const char* value(const ::robot_blockly::SetCurrentBlockId&) { return value(); }
};


// service_traits::MD5Sum< ::robot_blockly::SetCurrentBlockIdRequest> should match 
// service_traits::MD5Sum< ::robot_blockly::SetCurrentBlockId > 
template<>
struct MD5Sum< ::robot_blockly::SetCurrentBlockIdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_blockly::SetCurrentBlockId >::value();
  }
  static const char* value(const ::robot_blockly::SetCurrentBlockIdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_blockly::SetCurrentBlockIdRequest> should match 
// service_traits::DataType< ::robot_blockly::SetCurrentBlockId > 
template<>
struct DataType< ::robot_blockly::SetCurrentBlockIdRequest>
{
  static const char* value()
  {
    return DataType< ::robot_blockly::SetCurrentBlockId >::value();
  }
  static const char* value(const ::robot_blockly::SetCurrentBlockIdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_blockly::SetCurrentBlockIdResponse> should match 
// service_traits::MD5Sum< ::robot_blockly::SetCurrentBlockId > 
template<>
struct MD5Sum< ::robot_blockly::SetCurrentBlockIdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_blockly::SetCurrentBlockId >::value();
  }
  static const char* value(const ::robot_blockly::SetCurrentBlockIdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_blockly::SetCurrentBlockIdResponse> should match 
// service_traits::DataType< ::robot_blockly::SetCurrentBlockId > 
template<>
struct DataType< ::robot_blockly::SetCurrentBlockIdResponse>
{
  static const char* value()
  {
    return DataType< ::robot_blockly::SetCurrentBlockId >::value();
  }
  static const char* value(const ::robot_blockly::SetCurrentBlockIdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKID_H
