// Generated by gencpp from file robot_blockly/SetCurrentBlockIdResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKIDRESPONSE_H
#define ROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_blockly
{
template <class ContainerAllocator>
struct SetCurrentBlockIdResponse_
{
  typedef SetCurrentBlockIdResponse_<ContainerAllocator> Type;

  SetCurrentBlockIdResponse_()
    : result(false)  {
    }
  SetCurrentBlockIdResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetCurrentBlockIdResponse_

typedef ::robot_blockly::SetCurrentBlockIdResponse_<std::allocator<void> > SetCurrentBlockIdResponse;

typedef boost::shared_ptr< ::robot_blockly::SetCurrentBlockIdResponse > SetCurrentBlockIdResponsePtr;
typedef boost::shared_ptr< ::robot_blockly::SetCurrentBlockIdResponse const> SetCurrentBlockIdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_blockly

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/erle/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_blockly/SetCurrentBlockIdResponse";
  }

  static const char* value(const ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetCurrentBlockIdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_blockly::SetCurrentBlockIdResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKIDRESPONSE_H
