set(_CATKIN_CURRENT_PACKAGE "robot_blockly")
set(robot_blockly_MAINTAINER "Alejandro Hernández Cordero <ahcorde@erlerobot.com>, Víctor Mayoral Vilches <victor@erlerobot.com>")
set(robot_blockly_DEPRECATED "")
set(robot_blockly_VERSION "0.1.0")
set(robot_blockly_BUILD_DEPENDS "std_msgs" "message_generation")
set(robot_blockly_RUN_DEPENDS "std_msgs" "message_runtime")
set(robot_blockly_BUILDTOOL_DEPENDS "catkin" "message_runtime")