set(_CATKIN_CURRENT_PACKAGE "rosconsole_bridge")
set(rosconsole_bridge_VERSION "0.4.2")
set(rosconsole_bridge_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>, Ioan Sucan <isucan@gmail.com>")
set(rosconsole_bridge_BUILD_DEPENDS "libconsole-bridge-dev" "rosconsole")
set(rosconsole_bridge_BUILD_DEPENDS_rosconsole_VERSION_GTE "1.11.5")
set(rosconsole_bridge_RUN_DEPENDS "libconsole-bridge-dev" "rosconsole")
set(rosconsole_bridge_DEPRECATED "")
set(rosconsole_bridge_BUILDTOOL_DEPENDS "catkin")