set(_CATKIN_CURRENT_PACKAGE "genmsg")
set(genmsg_VERSION "0.5.6")
set(genmsg_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(genmsg_BUILD_DEPENDS )
set(genmsg_RUN_DEPENDS )
set(genmsg_DEPRECATED "")
set(genmsg_BUILDTOOL_DEPENDS "catkin")
set(genmsg_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.74")