set(_CATKIN_CURRENT_PACKAGE "roscpp_traits")
set(roscpp_traits_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(roscpp_traits_DEPRECATED "")
set(roscpp_traits_VERSION "0.5.6")
set(roscpp_traits_BUILD_DEPENDS )
set(roscpp_traits_RUN_DEPENDS "cpp_common" "rostime")
set(roscpp_traits_BUILDTOOL_DEPENDS "catkin")