// Generated by gencpp from file mavros_msgs/WaypointGOTO.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_WAYPOINTGOTO_H
#define MAVROS_MSGS_MESSAGE_WAYPOINTGOTO_H

#include <ros/service_traits.h>


#include <mavros_msgs/WaypointGOTORequest.h>
#include <mavros_msgs/WaypointGOTOResponse.h>


namespace mavros_msgs
{

struct WaypointGOTO
{

typedef WaypointGOTORequest Request;
typedef WaypointGOTOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointGOTO
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::WaypointGOTO > {
  static const char* value()
  {
    return "9a3be0c096ec7747147c283202a377db";
  }

  static const char* value(const ::mavros_msgs::WaypointGOTO&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::WaypointGOTO > {
  static const char* value()
  {
    return "mavros_msgs/WaypointGOTO";
  }

  static const char* value(const ::mavros_msgs::WaypointGOTO&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::WaypointGOTORequest> should match 
// service_traits::MD5Sum< ::mavros_msgs::WaypointGOTO > 
template<>
struct MD5Sum< ::mavros_msgs::WaypointGOTORequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros_msgs::WaypointGOTORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::WaypointGOTORequest> should match 
// service_traits::DataType< ::mavros_msgs::WaypointGOTO > 
template<>
struct DataType< ::mavros_msgs::WaypointGOTORequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros_msgs::WaypointGOTORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::WaypointGOTOResponse> should match 
// service_traits::MD5Sum< ::mavros_msgs::WaypointGOTO > 
template<>
struct MD5Sum< ::mavros_msgs::WaypointGOTOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros_msgs::WaypointGOTOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::WaypointGOTOResponse> should match 
// service_traits::DataType< ::mavros_msgs::WaypointGOTO > 
template<>
struct DataType< ::mavros_msgs::WaypointGOTOResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros_msgs::WaypointGOTOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_WAYPOINTGOTO_H
