set(_CATKIN_CURRENT_PACKAGE "rosunit")
set(rosunit_VERSION "1.11.11")
set(rosunit_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosunit_BUILD_DEPENDS )
set(rosunit_RUN_DEPENDS "python-rospkg" "roslib")
set(rosunit_DEPRECATED "")
set(rosunit_BUILDTOOL_DEPENDS "catkin")
set(rosunit_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")