set(_CATKIN_CURRENT_PACKAGE "geometry_experimental")
set(geometry_experimental_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(geometry_experimental_DEPRECATED "")
set(geometry_experimental_VERSION "0.5.12")
set(geometry_experimental_BUILD_DEPENDS )
set(geometry_experimental_RUN_DEPENDS "tf2" "tf2_bullet" "tf2_eigen" "tf2_geometry_msgs" "tf2_kdl" "tf2_msgs" "tf2_py" "tf2_ros" "tf2_sensor_msgs" "tf2_tools")
set(geometry_experimental_BUILDTOOL_DEPENDS "catkin")