# Generated by CMake 2.8.9

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target orocos-kdl
ADD_LIBRARY(orocos-kdl SHARED IMPORTED)

# Import target "orocos-kdl" for configuration "Release"
SET_PROPERTY(TARGET orocos-kdl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(orocos-kdl PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/erle/ros_catkin_ws/build_isolated/orocos_kdl/install/src/liborocos-kdl.so.1.3.0"
  IMPORTED_SONAME_RELEASE "liborocos-kdl.so.1.3"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
