set(_CATKIN_CURRENT_PACKAGE "pluginlib")
set(pluginlib_BUILD_DEPENDS_roslib_VERSION_GTE "1.11.1")
set(pluginlib_VERSION "1.10.1")
set(pluginlib_MAINTAINER "Esteve Fernandez <esteve@osrfoundation.org>")
set(pluginlib_BUILD_DEPENDS "boost" "cmake_modules" "class_loader" "rosconsole" "roslib" "tinyxml")
set(pluginlib_RUN_DEPENDS "boost" "class_loader" "rosconsole" "roslib" "tinyxml")
set(pluginlib_DEPRECATED "")
set(pluginlib_BUILDTOOL_DEPENDS "catkin")
set(pluginlib_RUN_DEPENDS_roslib_VERSION_GTE "1.11.1")
set(pluginlib_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")