set(_CATKIN_CURRENT_PACKAGE "roslint")
set(roslint_MAINTAINER "Mike Purvis <mpurvis@clearpathrobotics.com>, Alex Henning <ahenning@fetchrobotics.com>")
set(roslint_DEPRECATED "")
set(roslint_VERSION "0.10.0")
set(roslint_BUILD_DEPENDS )
set(roslint_RUN_DEPENDS )
set(roslint_BUILDTOOL_DEPENDS "catkin")