# CMake generated Testfile for 
# Source directory: /home/erle/ros_catkin_ws/src/ros_comm/topic_tools
# Build directory: /home/erle/ros_catkin_ws/build_isolated/topic_tools
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_topic_tools_rostest_test_shapeshifter.test "/home/erle/ros_catkin_ws/build_isolated/topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools/rostest-test_shapeshifter.xml" "--return-code" "/home/erle/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/topic_tools --package=topic_tools --results-filename test_shapeshifter.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/topic_tools/test/shapeshifter.test ")
ADD_TEST(_ctest_topic_tools_rostest_test_throttle.test "/home/erle/ros_catkin_ws/build_isolated/topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools/rostest-test_throttle.xml" "--return-code" "/home/erle/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/topic_tools --package=topic_tools --results-filename test_throttle.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/topic_tools/test/throttle.test ")
ADD_TEST(_ctest_topic_tools_rostest_test_throttle_simtime.test "/home/erle/ros_catkin_ws/build_isolated/topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools/rostest-test_throttle_simtime.xml" "--return-code" "/home/erle/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/topic_tools --package=topic_tools --results-filename test_throttle_simtime.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/topic_tools/test/throttle_simtime.test ")
ADD_TEST(_ctest_topic_tools_rostest_test_drop.test "/home/erle/ros_catkin_ws/build_isolated/topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools/rostest-test_drop.xml" "--return-code" "/home/erle/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/topic_tools --package=topic_tools --results-filename test_drop.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/topic_tools/test/drop.test ")
ADD_TEST(_ctest_topic_tools_rostest_test_relay.test "/home/erle/ros_catkin_ws/build_isolated/topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools/rostest-test_relay.xml" "--return-code" "/home/erle/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/erle/ros_catkin_ws/src/ros_comm/topic_tools --package=topic_tools --results-filename test_relay.xml --results-base-dir \"/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results\" /home/erle/ros_catkin_ws/src/ros_comm/topic_tools/test/relay.test ")
ADD_TEST(_ctest_topic_tools_nosetests_test.args.py "/home/erle/ros_catkin_ws/build_isolated/topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python" "/home/erle/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools/nosetests-test.args.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools" "/usr/local/bin/nosetests-2.7 -P --process-timeout=60 /home/erle/ros_catkin_ws/src/ros_comm/topic_tools/test/args.py --with-xunit --xunit-file=/home/erle/ros_catkin_ws/build_isolated/topic_tools/test_results/topic_tools/nosetests-test.args.py.xml")
