set(_CATKIN_CURRENT_PACKAGE "rosbash")
set(rosbash_VERSION "1.11.11")
set(rosbash_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosbash_BUILD_DEPENDS )
set(rosbash_RUN_DEPENDS "catkin")
set(rosbash_DEPRECATED "")
set(rosbash_BUILDTOOL_DEPENDS "catkin")
set(rosbash_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.72")