set(_CATKIN_CURRENT_PACKAGE "gencpp")
set(gencpp_VERSION "0.5.3")
set(gencpp_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(gencpp_BUILD_DEPENDS "genmsg")
set(gencpp_RUN_DEPENDS "genmsg")
set(gencpp_DEPRECATED "")
set(gencpp_BUILDTOOL_DEPENDS "catkin")
set(gencpp_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")