set(_CATKIN_CURRENT_PACKAGE "rosbuild")
set(rosbuild_VERSION "1.11.11")
set(rosbuild_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosbuild_BUILD_DEPENDS "pkg-config")
set(rosbuild_RUN_DEPENDS "catkin" "message_generation" "message_runtime")
set(rosbuild_DEPRECATED "")
set(rosbuild_BUILDTOOL_DEPENDS "catkin")
set(rosbuild_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")