set(_CATKIN_CURRENT_PACKAGE "genpy")
set(genpy_VERSION "0.5.6")
set(genpy_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(genpy_BUILD_DEPENDS "genmsg")
set(genpy_RUN_DEPENDS "genmsg")
set(genpy_DEPRECATED "")
set(genpy_BUILDTOOL_DEPENDS "catkin")
set(genpy_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")