set(_CATKIN_CURRENT_PACKAGE "actionlib_msgs")
set(actionlib_msgs_VERSION "1.11.8")
set(actionlib_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(actionlib_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(actionlib_msgs_RUN_DEPENDS "message_generation" "message_runtime" "std_msgs")
set(actionlib_msgs_DEPRECATED "")
set(actionlib_msgs_BUILDTOOL_DEPENDS "catkin")
set(actionlib_msgs_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")