set(_CATKIN_CURRENT_PACKAGE "roslib")
set(roslib_RUN_DEPENDS_python-rospkg_VERSION_GTE "1.0.37")
set(roslib_VERSION "1.11.11")
set(roslib_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(roslib_BUILD_DEPENDS "boost" "rospack")
set(roslib_RUN_DEPENDS "catkin" "python-rospkg" "rospack")
set(roslib_DEPRECATED "")
set(roslib_BUILDTOOL_DEPENDS "catkin")
set(roslib_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.6.7")