set(_CATKIN_CURRENT_PACKAGE "image_transport")
set(image_transport_MAINTAINER "Jack O'Quin <jack.oquin@gmail.com>, Vincent Rabaud <vincent.rabaud@gmail.com>")
set(image_transport_DEPRECATED "")
set(image_transport_VERSION "1.11.7")
set(image_transport_BUILD_DEPENDS "message_filters" "pluginlib" "rosconsole" "roscpp" "roslib" "sensor_msgs")
set(image_transport_RUN_DEPENDS "message_filters" "pluginlib" "rosconsole" "roscpp" "roslib" "sensor_msgs")
set(image_transport_BUILDTOOL_DEPENDS "catkin")