set(_CATKIN_CURRENT_PACKAGE "sick_tim")
set(sick_tim_MAINTAINER "Martin Günther <mguenthe@uos.de>")
set(sick_tim_DEPRECATED "")
set(sick_tim_VERSION "0.0.5")
set(sick_tim_BUILD_DEPENDS "roscpp" "sensor_msgs" "diagnostic_updater" "dynamic_reconfigure" "driver_base" "libusb-1.0-dev")
set(sick_tim_RUN_DEPENDS "roscpp" "sensor_msgs" "diagnostic_updater" "dynamic_reconfigure" "driver_base" "libusb-1.0")
set(sick_tim_BUILDTOOL_DEPENDS "catkin")